hpi-schul-cloud/antivirus_check_service

- ansible/roles/antivirus_check_service/templates/scanfile-deployment.yml.j2
- ansible/roles/antivirus_check_service/templates/web-deployment.yml.j2
Reduce resource consumption for deployed Antivirus Services.
https://ticketsystem.hpi-schul-cloud.org/browse/BC-37
https://ticketsystem.hpi-schul-cloud.org/browse/BC-90
Make CPU and memory resource consumption configurable.
Set the default for memory to be between 128mb and 1gb.
> BC-37 - BC-90 - reduce resource consumption for deployed Antivirus Services

- .github/workflows/main.yml
- .github/workflows/tag.yml
> fixup actions

- .github/workflows/main.yml
- .github/workflows/tag.yml
> Actions fixup

- .github/workflows/clean.yml
Fix for mistake on branch delete event.
It's not GITHUB_REF what shoud be usedm but github.event.ref.
The actions are triggered on the main branch, so GITHUB_REF shows to main and github.event.ref has the branchname of the deleted branch.
https://docs.github.com/en/rest/reference/git#delete-a-reference
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/3190
- https://github.com/hpi-schul-cloud/nuxt-client/pull/1959
- https://github.com/hpi-schul-cloud/schulcloud-client/pull/2716
- https://github.com/hpi-schul-cloud/schulcloud-calendar/pull/94
- https://github.com/hpi-schul-cloud/superhero-dashboard/pull/138
More and detailed information on the _definition of done_ can be found [on …
> BC-589 fix clean job

- ansible/group_vars/all/antivirus_check_service.yml
- ansible/roles/antivirus_check_service/templates/scanfile-deployment.yml.j2
- ansible/roles/antivirus_check_service/templates/web-deployment.yml.j2
https://ticketsystem.schul-cloud.org/browse/BC-740
https://ticketsystem.schul-cloud.org/browse/BC-852
> BC-740, BC-852 - rename image and tag vars

- ansible/roles/antivirus_check_service/tasks/main.yml
Change ansible module for rols
https://ticketsystem.hpi-schul-cloud.org/browse/BC-741
https://ticketsystem.hpi-schul-cloud.org/browse/BC-900
> BC-741 - BC-900 - Change ansible module for rols

- ansible/roles/antivirus_check_service/meta/main.yml
hpi-schul-cloud/dof_app_deploy#84
hpi-schul-cloud/nuxt-client#2017
hpi-schul-cloud/schulcloud-calendar#106
hpi-schul-cloud/schulcloud-client#2743
hpi-schul-cloud/schulcloud-server#3270
hpi-schul-cloud/superhero-dashboard#153
https://ticketsystem.hpi-schul-cloud.org/browse/BC-1006
> BC-1006 - Meta file for the roles

- setup.py
hpi-schul-cloud/schulcloud-server#3315
hpi-schul-cloud/schulcloud-client#2760
hpi-schul-cloud/nuxt-client#2041
hpi-schul-cloud/schulcloud-calendar#110
hpi-schul-cloud/superhero-dashboard#158
hpi-schul-cloud/dof_app_deploy#115
> version 2.0.2

- setup.py
hpi-schul-cloud/schulcloud-server#3327
hpi-schul-cloud/schulcloud-client#2769
hpi-schul-cloud/nuxt-client#2054
hpi-schul-cloud/schulcloud-calendar#113
hpi-schul-cloud/superhero-dashboard#162
hpi-schul-cloud/dof_app_deploy#134
> version 2.0.3

- antivirus_service/consumer.py
- antivirus_service/handler.py
- antivirus_service/service.py
- antivirus_service/webserver.py
> bc-1308 set content type and use exchange

- setup.py
> set release version 2.0.5

- antivirus_service/clamd.py
> BC-1395 improved exception logging

- setup.py
hpi-schul-cloud/schulcloud-server#3389
hpi-schul-cloud/schulcloud-client#2805
hpi-schul-cloud/nuxt-client#2110
hpi-schul-cloud/schulcloud-calendar#121
hpi-schul-cloud/schulcloud-synapse-synchronization#11
hpi-schul-cloud/superhero-dashboard#168
hpi-schul-cloud/dof_app_deploy#204
> version 2.1.0

- .github/workflows/push.yml
- .github/workflows/tag.yml
https://ticketsystem.dbildungscloud.de/browse/BC-2720
> BC-2720 update gh-actions

- .github/workflows/push.yml
- .github/workflows/tag.yml
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/420
> BC-2889 limit workflow permissions

- antivirus_service/handler.py
> BC-2698 - Return correct virus scan status

- .github/workflows/push.yml
- .github/workflows/tag.yml
https://ticketsystem.dbildungscloud.de/browse/BC-3778
> BC-3778 push container image to quay

- ansible/group_vars/all/antivirus_check_service.yml
https://ticketsystem.dbildungscloud.de/browse/BC-4316
https://github.com/hpi-schul-cloud/schulcloud-calendar/pull/139
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4207
https://github.com/hpi-schul-cloud/version-aggregator/pull/8
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3217
https://github.com/hpi-schul-cloud/nuxt-client/pull/2599
https://github.com/hpi-schul-cloud/superhero-dashboard/pull/214
https://github.com/hpi-schul-cloud/antivirus_check_service/pull/37
> BC-4316 pull images for ref and prod from quay.io

- requirements.txt
> BC-4685 fixing build by updating depdenencies

- .github/workflows/clean.yml
- .github/workflows/push.yml
- .github/workflows/tag.yml
https://ticketsystem.dbildungscloud.de/browse/BC-5855
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4655
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3374
https://github.com/hpi-schul-cloud/h5p-staticfiles-server/pull/8
https://github.com/hpi-schul-cloud/superhero-dashboard/pull/240
https://github.com/hpi-schul-cloud/nuxt-client/pull/2964
https://github.com/hpi-schul-cloud/antivirus_check_service/pull/49
https://github.com/hpi-schul-cloud/version-aggregator/pull/16
> BC-5658 update gh-actions, remove dof_bingo

- ansible/roles/antivirus_check_service/tasks/main.yml
- ansible/roles/antivirus_check_service/templates/scanfile-scaled-object.yml.j2
[BC-6559](https://ticketsystem.dbildungscloud.de/browse/BC-6559)
https://github.com/hpi-schul-cloud/antivirus_check_service/pull/51
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/792
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4758
> BC-6559 auto scale scanfile deployment on demand

- ansible/roles/antivirus_check_service/templates/scanfile-scaled-object.yml.j2
wrong scaleTargetRef, meant to be antivirus-scanfile-deployment
https://ticketsystem.dbildungscloud.de/browse/BC-6559
> BC-6559 api-worker-deployment -> scanfile-deployment

- ansible/roles/antivirus_check_service/templates/scanfile-scaled-object.yml.j2
currently keda creates an hpa which is basically maxed out for longer time thus might trigger a warning
to cicumvent that and ease it up a little we simply scale it up to max 2
https://ticketsystem.dbildungscloud.de/browse/BC-6937
> BC-6937 scale scan-file-deployment to max 2

- .github/workflows/push.yml
- ansible/roles/antivirus_check_service/tasks/main.yml
- hpi-schul-cloud/superhero-dashboard#262
- hpi-schul-cloud/dof_app_deploy#936
- hpi-schul-cloud/schulcloud-client#3509
- hpi-schul-cloud/schulcloud-server#5189
- hpi-schul-cloud/nuxt-client#3365
- hpi-schul-cloud/tldraw-client#80
- hpi-schul-cloud/version-aggregator#21
- hpi-schul-cloud/h5p-staticfiles-server#11
- hpi-schul-cloud/schulcloud-calendar#163
- hpi-schul-cloud/shd-client#7
- https://ticketsystem.dbildungscloud.de/browse/BC-7854
> BC-7854 - split Ansible Jobs by Tags

- antivirus_service/consumer.py
- antivirus_service/handler.py
- antivirus_service/service.py
https://ticketsystem.dbildungscloud.de/browse/BC-7972
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/954
> BC-7972 configureable retry mechanism

- antivirus_service/consumer.py
https://ticketsystem.dbildungscloud.de/browse/BC-8076
> BC-8052 set prefetch_size to 0 as its not supported by rabbitmq

- requirements.txt
https://ticketsystem.dbildungscloud.de/browse/BC-8082
> BC-8082 update dependencies

- ansible/roles/antivirus_check_service/templates/scanfile-deployment.yml.j2
- ansible/roles/antivirus_check_service/templates/web-deployment.yml.j2
Add annotations to the kubernetes deployments so that they cann automaticly restart by the stakater reloader if configmaps or secrets change 
- hpi-schul-cloud/schulcloud-server#5265
- hpi-schul-cloud/dof_app_deploy#981
- hpi-schul-cloud/schulcloud-client#3527
- hpi-schul-cloud/nuxt-client#3413
- hpi-schul-cloud/superhero-dashboard#267
- hpi-schul-cloud/shd-client#21
- hpi-schul-cloud/schulcloud-calendar#164
- hpi-schul-cloud/version-aggregator#23
- hpi-schul-cloud/h5p-staticfiles-server#12
- hpi-schul-cloud/tldraw-server#20
- hpi-schul-cloud/tldraw-client#100
- https://ticketsystem.dbildungscloud.de/browse/BC-5112
> BC-5112 - add Annotations to deployment for Restart

- Dockerfile
- requirements.txt
> BC-8523 update python to 3.13

- ansible/roles/antivirus_check_service/templates/scanfile-deployment.yml.j2
- ansible/roles/antivirus_check_service/templates/web-deployment.yml.j2
- https://ticketsystem.dbildungscloud.de/browse/BC-8876
- hpi-schul-cloud/dof_app_deploy#1100
- hpi-schul-cloud/schulcloud-server#5475
- hpi-schul-cloud/schulcloud-calendar#170
- hpi-schul-cloud/tldraw-server#52
- hpi-schul-cloud/schulcloud-client#3577
- hpi-schul-cloud/nuxt-client#3530
- hpi-schul-cloud/superhero-dashboard#277
- hpi-schul-cloud/version-aggregator#28
- hpi-schul-cloud/tldraw-client#123
- hpi-schul-cloud/h5p-staticfiles-server#17
- hpi-schul-cloud/shd-client#40
> BC-8876 - add os to the pod template from the deployment

- Dockerfile
- requirements.txt
https://ticketsystem.dbildungscloud.de/browse/BC-8965
https://github.com/hpi-schul-cloud/schulcloud-server/pull/5509
https://github.com/hpi-schul-cloud/nuxt-client/pull/3551
https://github.com/hpi-schul-cloud/superhero-dashboard/pull/280
https://github.com/hpi-schul-cloud/schulcloud-calendar/pull/172
https://github.com/hpi-schul-cloud/antivirus_check_service/pull/71
https://github.com/hpi-schul-cloud/tldraw-client/pull/124
https://github.com/hpi-schul-cloud/tldraw-server/pull/53
> BC-8965 fix container file warnings

- .github/dependabot.yml
- .github/workflows/push.yml
https://ticketsystem.dbildungscloud.de/browse/BC-9143
> BC-9143 add dependabot.yaml

- .github/workflows/push.yml
- .github/workflows/trivy.yml
https://ticketsystem.dbildungscloud.de/browse/BC-10096
https://github.com/hpi-schul-cloud/schulcloud-server/pull/5783
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3664
https://github.com/hpi-schul-cloud/nuxt-client/pull/3778
https://github.com/hpi-schul-cloud/superhero-dashboard/pull/315
https://github.com/hpi-schul-cloud/antivirus_check_service/pull/96
https://github.com/hpi-schul-cloud/version-aggregator/pull/37
https://github.com/hpi-schul-cloud/h5p-staticfiles-server/pull/21
https://github.com/hpi-schul-cloud/tldraw-client/pull/182
https://github.com/hpi-schul-cloud/tldraw-server/pull/68
https://github.com/hpi-schul-cloud/file-storage/pull/32
> BC-10096 update gh-actions
